import { PetModel } from './pet.model';

export const mockupData: PetModel[] = [
  {
    name: 'Luigy Gonzales',
    breed: 'Buldogue',
    gender: 'macho',
    color: 'preto',
    favorite: true,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Shakira Lopez',
    breed: 'Amarelo',
    gender: 'fêmea',
    color: 'amarelo',
    favorite: false,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Nico Di Angelo',
    breed: 'Frajola',
    gender: 'macho',
    color: 'preto e branco',
    favorite: true,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Bartolomeu II',
    breed: 'Vira-lata',
    gender: 'macho',
    color: 'preto e branco',
    favorite: false,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Marieta Soares',
    breed: 'Golden',
    gender: 'fêmea',
    color: 'marrom claro',
    favorite: false,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Pity Caramelo',
    breed: 'Vira-lata',
    gender: 'fêmea',
    color: 'caramelo',
    favorite: true,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Perseu Baptist',
    breed: 'Rajado',
    gender: 'macho',
    color: 'rajado',
    favorite: false,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Theodora Blanc',
    breed: 'Albino',
    gender: 'fêmea',
    color: 'branco',
    favorite: false,
    buttonLabel: 'Adote agora',
  },
  {
    name: 'Rosinha Mali',
    breed: 'Escaminha',
    gender: 'fêmea',
    color: 'preto e caramelo',
    favorite: true,
    buttonLabel: 'Adote agora',
  },
];
